language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-bootstrap-examples' ]; then cd .. && eval "mv $currentfolder generator-bootstrap-examples" && cd generator-bootstrap-examples; fi

